### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by MD211211** [Darkempire78/Mee6-Bypasser#16]
In token what do I put in config my discord token or ??

**Comment by MD211211** [comment]
ok i know where to out it now but this is my config and its ot working{
    "token": "BLAHBLAHBLAH(my real token i just dont wanna show it)",
    "removePreviousRewards": true,
    "updateEachMessage": true,
    "updateEachTime": [updateEachMessage]
}

**Comment by clementwzk** [comment]
updateEachMessage have to contain your guild id

e.g: "updateEachMessage": [0882927292873]

If you have an error, please write it...

**Comment by MD211211** [comment]
Ok I did that but the bot didn’t come online there is no error it just says starting forever and never starts?
