### ISSUE TITLE
ModuleNotFoundError - Help!

### ISSUE THREAD

**Issue by Dragon-720** [Darkempire78/Mee6-Bypasser#5]
![Screenshot (52)](https://user-images.githubusercontent.com/74246304/99870466-c5206980-2bdb-11eb-9be3-5e38c8576aa4.png)
Its giving me this error which I've never gotten before. Maybe this has something to do with the fact that I Installed Discord.py yesterday.
Please help!

**Comment by clementwzk** [comment]
Clearly you didn't install discord.py properly. Check if your interpreter's pip is the correct one. 
You might have installed it for python2.7.
