### ISSUE TITLE
Bot not working :/

### ISSUE THREAD

**Issue by Dragon-720** [Darkempire78/Mee6-Bypasser#7]
Lets me just say that this is honestly a very good bot and does what its supposed to do very nicely. The bot has been working for me very well up until now... It has suddenly stopped giving roles to people when they reach a certain level. The commands work but the bot does not give the roles. Let me say this again: It was working but now isnt for some reason. Do you know of any reasons that the bot wouldn't give the specified role? If so please help me fix this issue. Pherhaps someone can help me on discord. My username is sloth_on_meth#2646 . If you can help message me here or on discord @Darkempire78 could you give me your username so I could possibly send you a friend request?
Thanks

**Comment by clementwzk** [comment]
It's very strange because the bot works very well currently for me. 
I send you a friend request on Discord.

**Comment by clementwzk** [comment]
Simple error when he changed the code
